package ECMDatasetService;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "DatasetService", targetNamespace = "http://ws.dataservice.ecm.technology.totvs.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DatasetService {


    /**
     * 
     * @param companyId
     * @param password
     * @param username
     * @return
     *     returns ws.fluig.ECMDatasetService.AnyTypeArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "getAvailableDatasets")
    @WebResult(name = "datasets", partName = "datasets")
    public AnyTypeArray getAvailableDatasets(
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password)
        throws Exception_Exception
    ;

    /**
     * 
     * @param companyId
     * @param password
     * @param name
     * @param username
     * @throws Exception_Exception
     */
    @WebMethod(action = "deleteDataset")
    public void deleteDataset(
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "name", partName = "name")
        String name)
        throws Exception_Exception
    ;

    /**
     * 
     * @param companyId
     * @param password
     * @param username
     * @return
     *     returns ws.fluig.ECMDatasetService.FormDatasetDTOArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "findAllFormulariesDatasets")
    @WebResult(name = "dataset", partName = "dataset")
    public FormDatasetDTOArray findAllFormulariesDatasets(
        @WebParam(name = "companyId", partName = "companyId")
        long companyId,
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password)
        throws Exception_Exception
    ;

    /**
     * 
     * @param companyId
     * @param password
     * @param name
     * @param username
     * @return
     *     returns ws.fluig.ECMDatasetService.Dataset
     * @throws Exception_Exception
     */
    @WebMethod(action = "loadDataset")
    @WebResult(name = "dataset", partName = "dataset")
    public Dataset loadDataset(
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "name", partName = "name")
        String name)
        throws Exception_Exception
    ;

    /**
     * 
     * @param impl
     * @param companyId
     * @param password
     * @param name
     * @param description
     * @param username
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod(action = "addDataset")
    @WebResult(name = "dataset", partName = "dataset")
    public String addDataset(
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "description", partName = "description")
        String description,
        @WebParam(name = "impl", partName = "impl")
        String impl)
        throws Exception_Exception
    ;

    /**
     * 
     * @param impl
     * @param companyId
     * @param password
     * @param name
     * @param description
     * @param username
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod(action = "updateDataset")
    @WebResult(name = "dataset", partName = "dataset")
    public String updateDataset(
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "description", partName = "description")
        String description,
        @WebParam(name = "impl", partName = "impl")
        String impl)
        throws Exception_Exception
    ;

    /**
     * 
     * @param companyId
     * @param password
     * @param name
     * @param fields
     * @param constraints
     * @param username
     * @param order
     * @return
     *     returns ws.fluig.ECMDatasetService.DatasetDto
     * @throws Exception_Exception
     */
    @WebMethod(action = "getDataset")
    @WebResult(name = "dataset", partName = "dataset")
    public DatasetDto getDataset(
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "fields", partName = "fields")
        StringArray fields,
        @WebParam(name = "constraints", partName = "constraints")
        SearchConstraintDtoArray constraints,
        @WebParam(name = "order", partName = "order")
        StringArray order)
        throws Exception_Exception
    ;

}
